class DiagnosticsConfig:
    TRAFFIC_HEALTH_WEIGHT = 0.25
    CONVERSION_HEALTH_WEIGHT = 0.25
    SERVICE_HEALTH_WEIGHT = 0.25
    FINANCIAL_HEALTH_WEIGHT = 0.25

    TRAFFIC_CRASH_THRESHOLD = -20
    REFUND_RATE_WARNING = 15
    REFUND_RATE_CRITICAL = 20
    TOP5_TRAFFIC_CONCENTRATION_THRESHOLD = 50
    NATURAL_TRAFFIC_RATIO_THRESHOLD = 50
    NEW_CUSTOMER_RATIO_THRESHOLD = 70
    REPEAT_CUSTOMER_RATIO_TARGET = 40
    ZERO_SALE_RATIO_THRESHOLD = 40
    ROAS_TARGET = 3.5
    CPC_TARGET = 0.5
    CTR_TARGET = 4
    CONVERSION_RATE_TARGET = 6


class AnalysisConfig:
    DATE_FORMAT = '%Y-%m-%d'
    ANALYSIS_PERIOD_DAYS = 30
    HIGH_SEVERITY_THRESHOLD = 80
    MEDIUM_SEVERITY_THRESHOLD = 50


class ReportConfig:
    REPORT_OUTPUT_DIR = 'reports'
    REPORT_FILENAME_FORMAT = '店铺诊断报告_{date}.xlsx'
    CHART_OUTPUT_DIR = 'charts'